version: '3'

services:
  
  ae-node:
    image: aeternity/aeternity:v5.10.1
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    volumes:
      - ${PWD}/node/config/singlenode_mean15.yaml:/home/aeternity/aeternity.yaml
      - ${PWD}/node/config/accounts_test.json:/home/aeternity/node/data/aecore/.genesis/accounts_test.json
      - ${PWD}/node/keys/node1:/home/aeternity/node/keys
    ports:
     - "3013:3013"
     - "3113:3113"
     - "3014:3014"

  sophia-compiler:
    image: aeternity/aesophia_http:v4.3.2
    ports:
       - "3080:3080"

  redis:
    image: redis
    ports:
      - 6379:6379